---
name: Release on GitHub
on:
  workflow_call:
    inputs:
      tag_name:
        required: false
        type: string
        description: Git tag to create a release for
        default: null
      create_new_tag:
        required: false
        type: boolean
        description: Create a new tag if the input tag does not exist
        default: false
  workflow_dispatch:
    inputs:
      tag_name:
        required: false
        type: string
        description: Git tag to create a release for
        default: null
      create_new_tag:
        required: false
        type: boolean
        description: Create a new tag if the input tag does not exist
        default: false
defaults:
  run:
    shell: bash -euo pipefail {0}
    working-directory: .
jobs:
  github-release-with-current-tag:
    name: Create a GitHub release for the current tag
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    permissions:
      contents: write  # IMPORTANT: mandatory for making GitHub Releases
    env:
      GITHUB_TOKEN: ${{ github.token }}
    steps:
      - name: Validate the consistency
        if: inputs.tag_name != null && github.ref_name != inputs.tag_name
        run: >
          echo 'Invalid input tag: ${{ inputs.tag_name }} != ${{ github.ref_name }}'
          && exit 1
      - uses: actions/checkout@v4
      - name: Create the GitHub release for the tag
        run: >
          gh release create '${{ github.ref_name }}'
          --repo '${{ github.repository }}' --generate-notes --verify-tag
  github-release-with-input-tag:
    name: Create a GitHub release for the input tag
    if: (! startsWith(github.ref, 'refs/tags/'))
    runs-on: ubuntu-latest
    permissions:
      contents: write  # IMPORTANT: mandatory for making GitHub Releases
    env:
      GITHUB_TOKEN: ${{ github.token }}
    steps:
      - name: Validate the input tag
        if: inputs.tag_name == null
        run: >
          echo 'Input tag is required for non-tag events' && exit 2
      - uses: actions/checkout@v4
      - name: Create the GitHub release for the tag
        run: >
          gh release create '${{ inputs.tag_name }}'
          --repo '${{ github.repository }}' --generate-notes
          "$(${{ inputs.create_new_tag }} || echo '--verify-tag')"
